### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by v-Zak** [joeldavidson1/OOP-Assessment-1#1]
### **Code Review** 

**1. is the code properly documented/commented?** 

overall, the code is well documented and formatted with a consistent naming convention throughout with clear and understandable variable names. Classes contain a description at the top of their purpose in the program. All methods created include accurate descriptions on what they do and correctly outline the inputs and outputs of the methods. Within the methods most blocks of code are fully commented allowing quick debugging of each line. However, in only a few places I think there should be more comments as a lot of code is executed with minimal explanation. An example of this is in the program class, line 55 - 60, the code works but isn't explained. For example, a comment could be added above the LetterFrequency method call and output line saying something like "// Analyse letter frequencies and output it to the console".  

Areas where more comments could be beneficial are as follows.: 

Program.cs: 

line 24 - describe use of for loop to handle error 

line 55 - 60 - explain code in sub sections (refer example). 

  
Analyse.cs: 

line 96 - describe why a dictionary is created 

line 118 - 121 - move the split comment to above the line of code .Split and describe the words.Where line i.e., "create a list of words based on their length and then return" 

Input.cs: 

line 23 - "ask user for input and store as a variable text. Then check the input for errors" 

line 83 - similar to line 23 

InvalidSentenceException.cs: 

the custom class InvalidSentenceExeption doesn't contain a description of its purpose or a comment above its function outlining what it does. 

Report.cs: 

none 

**2. Does the code handle errors properly?** 

Input errors are handles exceptionally well, both during manual input and file input, with a custom exception even being used for errors during manual input. One thing of note for the inputs is that the valid file input method doesn't have a general exception at the end like the manual method does, so no error would be outputted to the user. If such an error did occur however the function would just endlessly run with no explanation as to why. 

One other area in Input.cs is in the FileTextInput() function. the ReadAllText() function called could return an error which would be unhandled. Try entering a blank path it crashes the program. 

As for the output, in Report.cs when outputting the long words text file, no error handling is used. for example, if the program has been previously run and the file permissions changed then an error would be thrown. 

But overall good use of errors. 

**3. Suggestions for improvement:** 

Before fixing the comments, I think it would be beneficial to consider the following improvements: 

Break up the analyse into separate functions for a cleaner AnalyseText() function, these functions would also be beneficial as if there was any future development on the project the functions could then be reused sticking to the DRY principle (Don't Repeat Yourself). So, within the for loop, you could call functions like CheckCharVowel() which could return a bool if the character is a vowel. This would increase overall line count but would make for a more understandable architecture which is more easily scalable and debuggable as each function can then be tested in isolation. As a general rule a base function should stick to doing one thing so separate functions would be used to check for the following: 

vowels, lowercase, uppercase, consonants, sentences 

these functions can then be reused elsewhere in other programs etc without any rewriting. 

Furthermore, referring to the DRY principle, in Program.cs both option 1 and 2 are very similar after the input text is created. At this point the analysis on the text is the same so should be done after the if statements to reduce repetition. the if statement would then only contain things that differ i.e., option 2 producing a list of long words. 

The way you calculate the number of sentences in a given piece of text assumed no repeated punctuality i.e., ... if such repetition occurs the sentence count is then wrong. A potential fix would be to keep track of the last character when looping through. If the last character was also an .? or ! then don't increment the counter. 

**4. Little nit-picks (maybe just personal preference :)):** 

while loops such as the one in Program.cs could use while(true) instead of a variable as then the break keyword can be used to exit out of the loop instead of changing the bool to false. 

var overused. Code still runs perfectly and reduces line count and character count but when it comes to readability it makes debugging harder as variable types are unclear when being skimmed over. An example of this is Program.cs line 59 where the LetterFrequency() function will always return a dictionary so the variable it is getting assigned to should also be a dictionary. 

**5. Summary:** 

Overall, a very good, concise and polished program with only a few minor errors that affect the running of the program with the rest being simple changes in readability and scalability.  

If you want any clarity on the issues raised, I'm more than happy to discuss in person.

**Comment by joeldavidson1** [comment]
Thank you for a thorough review. I've already amended most of these changes that you've stated :).
